### PR TITLE
json: Byte chunks should be appended to the end of final buffer

### PR DESCRIPTION
**Pull request by jaka**
I think the issue could be clarified from the proposed solution.

### CODE REVIEW

**Review by kostko — COMMENTED** [review]
Can you elaborate on what the problem was with the existing solution? As far as I see it, `buffer_len` is only used if the loop finishes. And in case `realloc` fails (signalling an out-of-memory condition) the function will return immediately.

**Comment by jaka** [comment]
`memcpy(buffer, tmp, n);` actually overwrites content of `buffer` in every iteration (does not append).
For example, if in first iteration `tmp = "abc"` and in second `tmp = "12"`, then `buffer = "12c"` and not `buffer = "abc12"` as I think it is expected.

I think this case have probably never occurred since `tmp` has a length of 1024 bytes and all strings that were read were shorter.

**Review by kostko — APPROVED** [review]
Nice catch, thanks!

**Comment by mitar** [comment]
I wonder, how have you found this? :-)

**Pull request merged**
